### PR TITLE
Add grape-active_model_serializers to /team.

### PR DESCRIPTION
**Pull request by drn**
@dblock, I've added grape-asm per your request.

@jrhe, I wasn't sure what location you wanted to use, so let me know and I'll update it.

### CODE REVIEW

**Comment by sssionggg** [comment]
@drn `Teng Siong Ong` instead of `Ten Siong Ong` :)

**Comment by drn** [comment]
@siong1987 - whoops! updated :)

**Comment by jrhe** [comment]
"London, UK" will do for now, although I may have to change it to "London,
England" at some point in the near future... Cheers :)

**Comment by drn** [comment]
Cool - updated the pull. This is ready to be merged in
screen shot 2016-07-14 at 11 12 30 am

**Comment by dblock** [comment]
@jrhe 🇬🇧 ;)

**Pull request merged**
