### PR TITLE
add Napa to Grape projects

### PR DESCRIPTION
**Pull request by shaqq**
@dblock 

Let me know if the copy is too long. I just copy/pasta'd.

### CODE REVIEW

**Comment by dblock** [comment]
I wouldn't mind a shorter one without the 'it's designed' part. But more importantly it's missing a period :)

**Comment by shaqq** [comment]
@dblock shortened it. shorter?

**Comment by dblock** [comment]
Great. Can you squash these? I know ... nitpicky me.

**Comment by shaqq** [comment]
@dblock no worries. Squashed.

**Comment by dblock** [comment]
Thanks!

**Pull request merged**
